version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: datascouting
      POSTGRES_USER: celani
      POSTGRES_PASSWORD: 112233!!
    ports:
      - "5666:5432"
    volumes:
      - pg_data_scouting:/var/lib/postgresql/data
  spring-boot:
    build:
      context: ./java
    image: openjdk:17-jdk-slim
    ports:
      - "8087:8087"
    depends_on:
      - postgres
  python-server:
    build: 
      context: ./python
    ports:
      - "8000:8000"

volumes:
  pg_data_scouting:
